### PR TITLE
Realm export normalization

### LINKED ISSUE #799: Normalized Export
### Problem Statement

(I'm not sure if this feature request is best placed here or in keycloak itself ... I'll first try here ...)

We use keycloak-config-cli to properly define the configuration of our Keycloak server in my-realm.json. That's great!

But we use manual configuration as well, usually because we need try and error to find the proper configuration.
To get manual changes into my-realm.json (and thus get a well-defined state again), we diff keycloaks export (kcadm.sh create realms/my-realm/partial-export) before and after the manual change. 

Problem with that is: the diff gets big, mostly because ordering in some of keycloaks arrays doesn't matter, and keycloak returns entries in different order. And because we regularly delete and create the realm from my-realm.json to play save - which causes Keycloak to choose new id s.

### Proposed Solution

Is it possible to provide normalized realm exports that:
* sorts arrays where ordering doesn't matter (e.g. protocolMappers and org.keycloak.keys.KeyProvider)
* normalize id s by replacing the uuids with a numbers: first with 1, then 2, etc

We currently use jq to manually do some normalization (see below). That helps us a lot, but it feels like a poor solution, especially replacing all id s with XXX ...

Best regards, Michael

#!/bin/sh
if [ "$#" -ne 1 ] ; then
  echo "Normalize arrays and ids"
  echo "usage: normalize.sh <src.json>"
  exit 1
fi
set -e

json=$(cat "$1")
json=$(echo "${json}" | jq '.clientScopes = (.clientScopes | sort_by(.name))')
json=$(echo "${json}" | jq '(.. | select(.protocolMappers?) | .protocolMappers) |= sort_by(.name)')
json=$(echo "${json}" | jq '(.components | .["org.keycloak.keys.KeyProvider"]) |= sort_by(.name)')
json=$(echo "${json}" | jq '(.components | .["org.keycloak.storage.UserStorageProvider"] | .[] | .subComponents | .["org.keycloak.storage.ldap.mappers.LDAPStorageMapper"]) |= sort_by(.name)')
json=$(echo "${json}" | jq '(.components | .["org.keycloak.services.clientregistration.policy.ClientRegistrationPolicy"]) |= sort_by(.name, .subType)')
json=$(echo "${json}" | jq '(.. | select(.["allowed-protocol-mapper-types"]?) | .["allowed-protocol-mapper-types"] ) |= sort')
json=$(echo "${json}" | jq '(.. | select(.id?) | .id) |= "XXX" ')
echo "${json}" | jq --sort-keys

### Environment

- Keycloak Version: 19.0.3
- keycloak-config-cli Version: 5.3.1
- Java Version: 17

### PR DESCRIPTION
**Pull request by sonOfRa**
**What this PR does / why we need it**:
When trying to move an existing keycloak installation with no configuration management to keycloak-config-cli, it can be hard to figure out which parts of the realm export are actually needed to reproduce the state when re-importing the configuration.

This PR can serve as a (partial) solution to this problem, by taking a realm export from a certain version of Keycloak, comparing it against a reference export of a "barebones" Keycloak realm from the same version, and then creating a yml (or JSON) file that only contains changes that are actually required.

This PR will not be a *complete* solution that works for all cases, but it will supply an at least somewhat minimized view of clients and some related settings, which can then easily be merged with a full export in order to get a smaller view of the file. Support for additional parts (identity providers, authentication flows, etc) can be added in later steps to improve this export.

This PR includes a "mode switch" that allows users to switch between IMPORT and NORMALIZE modes using the property ``run.operation=NORMALIZE``. IMPORT is the default, and is used when no option is supplied by the user.

This PR includes an upgrade to Spring Boot 2.7.5, which contains a fix for https://github.com/spring-projects/spring-boot/issues/32559. The ``@DefaultValue`` annotation is used to move configuration from the default application.properties file directly to the code. This is needed so that only the needed configurations for the chosen mode (IMPORT or NORMALIZE) are activated.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #799

**Special notes for your reviewer**:
A custom properties ``application-normalize-dev.properties`` file for testing the export functionality was added. Activating this profile enables normalization mode, and expects an input realm to be present at the top-level exports directory

```
exports
├── in
│   └── realm.json
└── out
    └── demo1234.yaml
```
The file `in/realm.json` will be imported, and the file `out/demo1234.yaml` is created by the process, where the realm name of the input realm is `demo1234`

Run the application with the   `normalize-dev` profile active to normalize a given realm. 

The configuration parameter `normalization.output-format` can be used to switch between YAML (the default, if no option is given) and JSON output.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by manuschillerdev** [comment]
Would be possible via some kind of diffing to keep params for fields with env var substitutions?

Example: 

```json
{
  "realm": "my-realm",
  "smtpServer": {
    "replyToDisplayName": "$(env:SMTP_REPLY_TO_DISPLAYNAME)",
    "port": "$(env:SMTP_PORT)",
    "host": "$(env:SMTP_HOST)",
    "replyTo": "$(env:SMTP_REPLY_TO)",
    "from": "$(env:SMTP_FROM)",
    "fromDisplayName": "$(env:SMTP_FROM_DISPLAY_NAME)",
    "envelopeFrom": "$(env:SMTP_ENVELOPE_FROM)"
  },
  ```
  
When I import this realm, make changes and export the realm again I'd like to keep the params for SMTP instead of having to replace the actual values from the export with the parameters again.
  
 I have no idea what that means regarding the implementation. Just as an idea to make working with the huge JSON-Files easier :)

**Comment by sonOfRa** [comment]
@manuschillerdev I think that might be a valuable future extension of this feature!

In theory, one could provide a map of "reverse injections" where you specify something like "When the field `realm.smtpServer.host` has the same value as the resolved environment variable "SMTP_HOST", then replace the value with `$(env:SMTP_HOST)`. This seems to me like a valuable addition to this feature in order to make the process of going from "I have a keycloak instance that has been configured via admin-ui" to "I have a relatively minimal yaml file that represents my config state"

However, I think I'd like to get the base idea of this PR (minimize a realm.json acquired from a full Keycloak realm export) done first, and then build additional features on top of that

**Comment by weand** [comment]
i tried this PR on KC20.0.5.

After adding baseline files for 20.0.5 and building the cli, following error occurs when running it against our existing realm. Seems like there are `remove(...)` calls on an immutable map...
```
Caused by: java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.remove(ImmutableCollections.java:1075)
        at de.adorsys.keycloak.config.service.normalize.RoleNormalizationService.normalizeClientRoles(RoleNormalizationService.java:83)
        at de.adorsys.keycloak.config.service.normalize.RoleNormalizationService.normalizeRoles(RoleNormalizationService.java:57)
        at de.adorsys.keycloak.config.service.normalize.RealmNormalizationService.normalizeRealm(RealmNormalizationService.java:150)
        at de.adorsys.keycloak.config.KeycloakConfigNormalizationRunner.run(KeycloakConfigNormalizationRunner.java:92)

**Comment by sonOfRa** [comment]
Hi @weand!

Can you provide a realm export for the realm you tried this on? Note that realm exports will contain sensitive data like the client secrets and all your realm keys (for signing JWTs). If it's not possible to censor the realm enough for it to be exportable to a public place, could you maybe find a certain configuration of roles that triggers this bug? I'll also take a look in the meantime if I can find what causes this.

**Comment by weand** [comment]
@sonOfRa Check this reproducer export [realm-export-uoe.zip](https://github.com/adorsys/keycloak-config-cli/files/10969577/realm-export-uoe.zip)

It's as simple as this: Simply disable one of the default clients, e.g. `realm-management` and `security-admin-console` in my example.

BTW: I could not figure out how to enable debug output (which prints the root exception). With that:
```
java -Dspring.profiles.active=debug \
  -jar $script_dir/keycloak-config-cli-20.0.5.jar \
  --normalization.files.inputLocations=$script_dir/normalize/in/*.json \
  --normalization.files.outputDirectory=$script_dir/normalize/out \
  --run.operation=NORMALIZE
  --debug
```

Log looks like this:
```
2023-03-14 15:09:13.382  INFO 2360748 --- [           main] d.a.k.c.s.n.RealmNormalizationService    :
 Exporting realm foo-bar
2023-03-14 15:09:13.486 ERROR 2360748 --- [           main] .a.k.c.KeycloakConfigNormalizationRunner :
 null
```

To see the root exception I had to remove that condition
```
https://github.com/sonOfRa/keycloak-config-cli/blob/feature/export-diff-yaml/src/main/java/de/adorsys/keycloak/config/KeycloakConfigNormalizationRunner.java#L112-L114
```

Any advice on how  to run with debug output enabled would be great.

**Comment by francis-pouatcha** [comment]
@jonasvoelcker what do you think. Can we look deeper into this feature?

**Comment by jonasvoelcker** [comment]
Hi @francis-pouatcha,

as mentioned in one of the other merge requests I am currently not available for any work on community things. Our project requires other things and additionally I am about to get a second child in a few days so I can't invest any freetime 😉

Best Regards
Jonas

**Comment by sonOfRa** [comment]
I currently cannot spare time to work on this PR further; I switched to another employer and we're not using the feature here. But if any of the people trying to use the feature are willing to take over development on this PR, feel free to do so; I place the changes I've made here in the public domain and anyone is free to use them to continue development of this feature with my changes as a base

**Comment by srose** [comment]
Maybe talk about the topic in Vienna tomorrow?

**Comment by thomasdarimont** [comment]
I just gave this a spin and aligned the changes from this branch with the latest keycloak-config-cli version in main
https://github.com/thomasdarimont/keycloak-config-cli/tree/feature/realm-normalization
I integrated all commits from this PR with one merge commit with proper config resolutions. I then did minimal changes to adapt the code for the newer Spring Boot version 3.x. I did only minimal changes to get it working again. I think this needs some refactoring and could also be extended to support a "realm export" from an "live" realm.

The build works again I could successfully "normalize" a realm export generated from KC 25.0.5.
See: https://gist.github.com/thomasdarimont/7c434fe6dcf20fa28a06cc38e15d6105

**Comment by francis-pouatcha** [comment]
@thomasdarimont would you send a pull request to sonOfRa:feature/export-diff-yaml or to adorsys:main?

**Comment by thomasdarimont** [comment]
@francis-pouatcha I rebased this branch and adapted it to the current main. I had to squash most commits to ease the rebase. I added @sonOfRa as coauthor of the new PR.

See: https://github.com/adorsys/keycloak-config-cli/pull/1207

**Comment by sonOfRa** [comment]
Thanks for taking over, @thomasdarimont, I'll close this PR in favor of yours then.

**Pull request closed without merging**
