### PR TITLE
Client scope mapping fix

### PR DESCRIPTION
**Pull request by Oh-tech**
Please consider the fix of the #360 issue

### CODE REVIEW

**Comment by jkroepke** [comment]
Is the PR done? (Draft mode)

**Comment by jkroepke** [comment]
Hi,

thanks for providing a solution for #360 . I would appreciate it if you add a the change log entries for the changes, too. Talking about multiple, since you are resolve #360 + it looks like you also adding client roles on client scope mappings.

What happens, if a client inside the import json does not have a clientId but a name defined? I thought keycloak-config-cli cloud match a client by name, if no clientId was specified. But looking at the code (existing or this one), this was never true.

**Comment by Oh-tech** [comment]
Hi 
I added the changelog items, please have a look.

Answering your question, now clients without client id specified will cause the `KeycloakRepositoryException` exc eption. Please take a look at the `ImportClientsIT.shouldNotUpdateRealmByAddingInvalidClient`.

And having such an opportunity I would like to say a big thanks to the community for such nice tools. it really makes life easier. Thank you, guys!

**Comment by jkroepke** [comment]
Hi @Oh-tech,

thanks for the goodies :)

Currently, I'm testing this PR by an additional test https://github.com/adorsys/keycloak-config-cli/commit/7cc82957d9b6d74af17739052ab1134124edce8c but the additional test is failing. I had to verify if the code has issues or the test itself.

**Comment by jkroepke** [comment]
Hi @Oh-tech 

I added a test case which edit an existing 2nd clientScopeMappings but the tests are failing. Did you have any idea whats going wrong here?

**Comment by Oh-tech** [comment]
Hi @jkroepke 

I will check that

**Comment by Oh-tech** [comment]
Hi @jkroepke.

Please have a look, I've fixed the issue.

**Comment by jkroepke** [comment]
Great thanks a lot!

I have one last question:

I look at main branch, it's possible to configure client without define a client id. I test that. Without define a client id I could still update an existing client using the name an identifier. Using this mechanism, it's possible to configure client created by keycloak without known the client id.

This PR marks the clientId field as required which is a **backwards incompatible change**.

It's possible to restore the old behavior from main branch?

**Edit:** I test two clients without define a clientId and they start to override each other. Looks like

> The ClientRepository.searchByClientId(String realmName, String clientId) method returns the first client of the realm when the clientId parameter is null.

This the issue here, I may add some doing in a followup PR.

**Pull request merged**
