### PR TITLE
Add Keycloak 23

### LINKED ISSUE #948: Add support for Keycloak 23.0.0
### Problem Statement

Keycloak 23.0.0 is currently not compatible with keycloak-config-cli version 5.9.0.

### Proposed Solution

_No response_

### Environment

- Keycloak Version: 23.0.0
- keycloak-config-cli Version: 5.9.0
- Java Version: 17

### Additional information

_No response_

### Acceptance Criteria

_No response_

### PR DESCRIPTION
**Pull request by jonasvoelcker**
**What this PR does / why we need it**:

This is needed to make keycloak-config-cli compatible with Keycloak 23.

**Which issue this PR fixes** Fixes #948 & #884

**Special notes for your reviewer**:

* Updated CI to use Keycloak 23.0.1
* Added correct spelling of "authenticatorFlow" in all import files
* Treating default-roles-${realm} as default role even with changed description
* Supporting new group handling, also loading sub groups manually
* Supporting new user profile configuration (UPConfig)
* Removed deprecated authenticator "registration-profile-action" from tests
* Extended maven-replacer-plugin with breaking changes
* Using util classes as replacement strategy for breaking changes (GroupUtil, SubGroupUtil)

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

* [x]  the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by jonasvoelcker** [comment]
There is still some problem with a NullPointerException where the GroupResource could not be correctly loaded. This is a flaky test and I don't tend to add a Null-Check to avoid imports being incomplete instead of telling the team to rerun the import.

**Comment by thomasdarimont** [comment]
@jonasvoelcker thanks for picking the work up from #952.

Did you take notice that Keycloak is currently reworking some changes in the group API?
"Meaning of briefRepresentation query parameter is inverted in GroupResource.getSubGroups": https://github.com/keycloak/keycloak/issues/25096
"RealmAdminResource.getGroupByPathGroup does not work with space in path parameter": https://github.com/keycloak/keycloak/issues/25111

**Comment by thomasdarimont** [comment]
@jonasvoelcker IMHO those artifacts / images will not be overridden, but I assume we will get new releases, either a 23.0.x or a 24.0.x with the "corrected" (groups) behaviour.

**Comment by jonasvoelcker** [comment]
@thomasdarimont Then we should build a new profile for 23.0.0 and 23.0.1 which replaces the Util-Classes with my patched versions, which then be renamed to .java.intermediate or something like that. Therefore we also have compatibility for those two versions.

**Comment by alwibrm** [comment]
Any idea when this gets reviewed / merged?

**Comment by jonasvoelcker** [comment]
Hey @alwibrm,

I've already reached out to @st3v0rr, he'll take his time soon 😉

**Pull request merged**
