### PR TITLE
Validate composite client roles

### PR DESCRIPTION
**Pull request by daniel-shuy**
When declaring a non-existent composite client role (eg. typo), `keycloak-config-cli` fails with a HTTP `500` error, with no detailed error message. Looking into the Keycloak logs reveals that Keycloak fails internally with a `NullPointerException`.

As an improvement, validate the composite client roles, and log a readable error message if any do not exist.

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi @daniel-shuy 

can you provide a test case for this error scenario?

**Comment by daniel-shuy** [comment]
@jkroepke Sorry, didn't have time to do it, thanks for helping to add the tests!

**Comment by daniel-shuy** [comment]
@jkroepke I had to recommit my changes because I previously used the wrong email address in the commit. In the process I had to cherry-pick your commit, which caused it to no longer be signed. Since you have vigilant mode enabled you'll have to re-sign it, sorry for the inconvenience.

**Comment by jkroepke** [comment]
Thanks for the contribution!

**Comment by daniel-shuy** [comment]
Glad to contribute to this awesome tool!

**Pull request merged**
