### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by BreakBB**
**What this PR does / why we need it**:

The wording of the log message printed after config-cli finished successfully was not correct. This PR fixes it.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by BreakBB** [comment]
Coverage upload to codecov failed in the build CIs. Doesn't look like something I can fix.

**Comment by BreakBB** [comment]
Anything I can do to get this merged?

**Comment by jonasvoelcker** [comment]
Hi @BreakBB,

could you please rebase your PRs onto the current main so we can see whether the Github Actions work now?

Best Regards
Jonas

**Review by jonasvoelcker — APPROVED** [review]

**Comment by BreakBB** [comment]
Thanks for taking care of the rebase and merging this @jonasvoelcker

**Pull request merged**
