### PR TITLE
Fix to prevent realm state overwriting during realm update when realm attributes are specified in a config file

### PR DESCRIPTION
**Pull request by Oh-tech**

### CODE REVIEW

**Comment by Oh-tech** [comment]
Fixes the issue #478

**Comment by jkroepke** [comment]
Hi @Oh-tech 

thanks for this great catch! But it not resolve the issue completely.

In case there is a fatal error while upgrade, the state is still missing in the realm.

**Comment by Oh-tech** [comment]
Hi @jkroepke 
Yes, correct. An alternative might be only filling the `attributes` with the state values before running the update. 
What do you think?

**Comment by Oh-tech** [comment]
Hi @jkroepke 

Looks like it has to fix the issue which you mentioned. Please review.

**Comment by jkroepke** [comment]
Looks good to me.

> In case there is a fatal error while upgrade, the state is still missing in the realm.

Can you provide a test for that specific usecase?

For example, to could introduce an fatal error, by define a client like that:

https://github.com/adorsys/keycloak-config-cli/blob/main/src/test/resources/import-files/clients/90_update_realm__try-to-create-client.json

**Comment by Oh-tech** [comment]
Yeah, will do :)

**Comment by Oh-tech** [comment]
Hi @jkroepke.

Done, please have a look.

**Comment by jkroepke** [comment]
Thanks

**Pull request merged**
