### PR TITLE
Fix: importing more than 10 subgroups

### LINKED ISSUE #1014: Cannot create 20 or more subGroups
### Current Behavior

Cannot create 20 or more subGroups

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at de.adorsys.keycloak.config.KeycloakConfigApplication.main(KeycloakConfigApplication.java:35)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.idm.GroupRepresentation.getRealmRoles()" because "existingGroup" is null
        at de.adorsys.keycloak.config.service.GroupImportService.addRealmRoles(GroupImportService.java:175)
        at de.adorsys.keycloak.config.service.GroupImportService.addSubGroup(GroupImportService.java:213)
        at de.adorsys.keycloak.config.service.GroupImportService.addSubGroups(GroupImportService.java:202)
        at de.adorsys.keycloak.config.service.GroupImportService.createGroup(GroupImportService.java:151)
        at de.adorsys.keycloak.config.service.GroupImportService.createOrUpdateRealmGroup(GroupImportService.java:139)
        at de.adorsys.keycloak.config.service.GroupImportService.lambda$createOrUpdateGroups$0(GroupImportService.java:77)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at de.adorsys.keycloak.config.service.GroupImportService.createOrUpdateGroups(GroupImportService.java:81)
        at de.adorsys.keycloak.config.service.GroupImportService.importGroups(GroupImportService.java:69)
        at de.adorsys.keycloak.config.service.RealmImportService.configureRealm(RealmImportService.java:203)
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealm(RealmImportService.java:195)
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealmIfNecessary(RealmImportService.java:153)
        at de.adorsys.keycloak.config.service.RealmImportService.doImport(RealmImportService.java:144)
        at de.adorsys.keycloak.config.KeycloakConfigRunner.run(KeycloakConfigRunner.java:79)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
        ... 13 common frames omitted
```

### Expected Behavior

Create more than 20 subGroups, divided into one or more groups

### Steps To Reproduce

With this config :
```markdown
id: master
realm: master
displayName: Keycloak
enabled: true
userManagedAccessAllowed: true
eventsEnabled: true
adminEventsEnabled: true
rememberMe: true
bruteForceProtected: true
failureFactor: 5
internationalizationEnabled: true
passwordPolicy: "length(8) and specialChars(1) and upperCase(1) and lowerCase(1) and digits(1)"
supportedLocales:
- en
- fr
- es

groups:
- name: group
  subGroups:
    - name: group1
    - name: group2
    - name: group3
    - name: group4
    - name: group5
    - name: group6
    - name: group7
    - name: group8
    - name: group9
    - name: group10
    - name: group11
    - name: group12
    - name: group13
    - name: group14
    - name: group15
    - name: group16
    - name: group17
    - name: group18
    - name: group19
    - name: group20
    - name: group21
    - name: group22
    - name: group23
    - name: group24
    - name: group25
    - name: group26
```

And run java -jar keycloak-config-cli.jar

### Environment

- Keycloak Version: 24.0.3
- keycloak-config-cli Version: 5.12.0
- Java Version: 17

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by timadevelop**
**What this PR does / why we need it**:

- for reference: https://github.com/adorsys/keycloak-config-cli/issues/1014#issuecomment-2168046857

**Which issue this PR fixes** : fixes #1014 

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by jonasvoelcker — APPROVED** [review]
Looks very promising :)

**Comment by jonasvoelcker** [comment]
Hi @timadevelop,

thanks for your contribution so far, it seems like you are on the right track. Unfortunately the SubGroupUtil.java.legacy handles the subgroups a little different and as we support also older version, it might be good to separate the initial test from the one with many subgroups.

Would it be possible that you maybe add this scenario as @Order(48) with a separate json-file so we can add this line to ignore it for older Keycloak versions?

`assumeTrue(VersionUtil.ge(KEYCLOAK_VERSION, "23"));`

Best Regards
Jonas

**Comment by timadevelop** [comment]
@jonasvoelcker done ✅ . Also fixed the `98/shouldUpdateRealmDeleteGroup` test, it depended on groups from 47th one (hence new one interfered with it).

**Comment by jonasvoelcker** [comment]
@timadevelop I've changed the order as no init step is needed that way. ;)

**Pull request merged**
