### PR TITLE
Refactor user profile support

### LINKED ISSUE #815: Refactor User Profile Support
### Problem Statement

- Responses are currently not closed properly
- Some data is fetched even it is potentially not used 
- Some log messages use level info but should use trace

### Proposed Solution

- close responses where necessary
- only fetch data when needed
- change log level to trace for tracing messages

### Environment

- Keycloak Version: [e.g. 10.0.1]
- keycloak-config-cli Version: [e.g. 1.4.0]
- Java Version: [e.g. 11]

### Additional information

_No response_

### Acceptance Criteria

_No response_

### PR DESCRIPTION
**Pull request by thomasdarimont**
- Use log level trace instead of info for instrumentation
- Ensure http responses are closed properly
- Improve naming and fix typos

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #815

**Special notes for your reviewer**:
- The info log level produces noise during clean runs
- Response resource handling was not an issue for large realms but better be save than sorry.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by srose — APPROVED** [review]

**Comment by srose** [comment]
LGTM

**Comment by thomasdarimont** [comment]
@st3v0rr FYI this is ready for review and can be considered for a maintenance release.

**Comment by thomasdarimont** [comment]
@st3v0rr any idea when this could get merged?

**Comment by dvdgsng** [comment]
We'd like to see this merged as well. When configuring a realm with multiple files, config-cli is quite to verbose, atm.

```
d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v5.6.1 using Java 17.0.6 on e41d5c3e32c8 with PID 227 (/keycloak-config-cli.jar started by keycloak in /)
d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 0.615 seconds (JVM running for 0.851)
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/00_master.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/01_company_event_listeners.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/10_company_realm.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/11_company_supergroup.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/20_company_roles_modules.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/21_company_roles_user.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/22_company_default_role.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/30_company_client_scopes_company.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/31_company_client_scopes_company_internal.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/32_company_client_scopes_company_federation.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/33_company_client_scopes_company_idp.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/50_company_clients_company.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/51_company_clients_company_api.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/59_company_clients_company_add_redirects.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/61_company-superadmin.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/tmp/tmp.t0A6sFw1cM/99_company_password_policy.yaml'
d.a.k.c.s.UserProfileImportService       : UpdateProfile realm-attribute 'userProfileEnabled' not set: skipped.
d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 00:04.469.
```

**Pull request merged**
