### PR TITLE
Add support for Setting unmanagedAttributePolicy

### LINKED ISSUE #1016: Can't set unmanagedAttributePolicy in userProfile
### Current Behavior

When trying to add `unmanagedAttributePolicy` to the `userProfile` configuration (see config example below), the keycloak-config-cli throws an error.
Config:
```yaml
realm: realm-test
displayName: "Realm Test"
enabled: true
userProfile:
  - name: username
    displayName: "${username}"
    validations:
      length:
        min: 3
        max: 255
      username-prohibited-characters: { }
  unmanagedAttributePolicy: "ENABLED"
```

Error:
```
2024-05-08 22:33:45.306 ERROR 408 --- [           main] d.a.k.config.KeycloakConfigRunner        : Unable to parse file 'file:/opt/keycloak/data/import/realm.yaml': Cannot deserialize value of type `java.util.ArrayList<java.util.Map<java.lang.String,java.lang.Object>>` from String value (token `JsonToken.VALUE_STRING`)
at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: de.adorsys.keycloak.config.model.RealmImport["userProfile"]->java.util.LinkedHashMap["unmanagedAttributePolicy"])
```

### Expected Behavior

The keycloak-config-cli should be able to configure the `unmanagedAttributePolicy` with the corresponding value set (e.g. `ENABLED`, `DISABLED`, `ADMIN_EDIT`, ETC) and no error should be thrown.

### Steps To Reproduce

```markdown
Call the keycloak-config-cli using a config that contains the `userProfile.unmanagedAttributePolicy`, as provided in the example above.
```

### Environment

- Keycloak Version: [24.0.3]
- keycloak-config-cli Version: [5.12.0]
- Java Version: [17]

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by antikalk**
**What this PR does / why we need it**: Added ITs for setting the `unmanagedAttributePolicy`

**Which issue this PR fixes**: fixes #1016 

**Special notes for your reviewer**: This feature is already implemented. Never the less, this PR adds some integration tests.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by AssahBismarkabah — COMMENTED** [review]
Hello @antikalk, the ticket  https://github.com/adorsys/keycloak-config-cli/issues/1016 has not been implemented yet. Closing this ticket will also close it now.

**Comment by antikalk** [comment]
Hi @AssahBismarkabah 

When I started implementing https://github.com/adorsys/keycloak-config-cli/issues/1016, I realized that the feature has already been implemented previously - with some update config-cli started to support the `unmanagedAttributePolicy` property. 

Since I already started with writing the integration tests for this feature, I think it would be a nice addition to include them.

**Comment by AssahBismarkabah** [comment]
Hi @antikalk ok then, but it will be nice if the conflicts with the base branch can be resolved.

**Comment by robson90** [comment]
Hey @antikalk, could you please resolve the conflicts ? 

Thanks for creating this PR, much appreciated!

**Comment by robson90** [comment]
Hey @AssahBismarkabah is there a timeline, when you guys will release a new version with this change ?

**Comment by AssahBismarkabah** [comment]
Hello @robson90 ,
We will coordinate internally and provide you with feedback shortly.
Thank you.

**Pull request merged**
