### PR TITLE
Fix docker hub link creation for releases

### PR DESCRIPTION
**Pull request by BreakBB**
**What this PR does / why we need it**:
Currently the link generated for the release body has the following format:

> https://hub.docker.com/r/adorsys/keycloak-config-cli/tags?name=v5.12.0

However the docker images omit the `v`-prefix, so these links don't provide any results.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by jonasvoelcker** [comment]
Hi @BreakBB,

could you please rebase your PRs onto the current main so we can see whether the Github Actions work now?

Best Regards
Jonas

**Comment by jonasvoelcker** [comment]
Hi @francis-pouatcha,
would you be so kind to take a look at this change, whether it might do the job or not?

**Comment by BreakBB** [comment]
Thanks for actually fixing the issue @jonasvoelcker At a second glance `TAG#v` indeed looks like the better/correct way.

**Review by francis-pouatcha — APPROVED** [review]
Looks good for me!

**Comment by jonasvoelcker** [comment]
Hi @BreakBB,

unfortunately our change resulted in an even worse solution: https://github.com/adorsys/keycloak-config-cli/releases/tag/v6.0.0

We have reverted the change so it is the same as before:

https://github.com/adorsys/keycloak-config-cli/releases/tag/v6.0.2

If you feel like we need that change, please try to provide another PR, in my opinion it is not that urgent, right?

Best Regards
Jonas

FYI: @francis-pouatcha @st3v0rr

**Comment by BreakBB** [comment]
Oh wow, yeah that is absolutely not how it should look like, sorry.

Yeah, it's not urgent at all. I was initially thinking about providing a simple and quick fix. I'll see if I can open a test repository to test the pipeline and find a proper solution.

**Pull request merged**
