### PR TITLE
Support for Adding, Updating and Removing clientScopes

### PR DESCRIPTION
**Pull request by spahrson**
This pull request adds support for adding, updating and removing clientScopes. It includes a check to ignore the default default and default optional clientScopes like e.g. `address`  or `offline_access`. It fetches this default scopes from the current realm.

### CODE REVIEW

**Comment by spahrson** [comment]
Hi, acutally the Test `de.adorsys.keycloak.config.ImportExportedRealmIT.shouldImportExportedRealm` is failing. I will check asap if this happens because of my changes.

**Comment by jkroepke** [comment]
Hi,

thanks the PR! I have a question:

This pull request implement a function called `deleteAllExistingClientScopes`.

Reading the code the function is triggered if the config contains an `clientScopes` entry with an empty array. If `clientScopes` isn't defined, nothing will be delete. This is correct? Could you add a test case for this? If the project gets refactored at sometime, the tests can help to avoid passive breaking changes.

Aside from this pull request, a delete all function could be dangerous. What did you think something about a force switch? A user should confirm such dangerous actions by setting a properties/switch.

Please rename the directory in `import-files/clientScopes` to `import-files/client-scopes` to be consistent with other directory names.

**Comment by spahrson** [comment]
Thank you for your feedback. I renamed the directory and added the missing tests.

I saw this principle in the `RoleImportService`. I like this way of dealing with resources because it allows to split resources (e.g. clients, roles or clientscopes) into different files. 

Regarding the idea of a force switch:

I personally would prefer an "ignore" switch to a "force" switch. In my opinion it is a special requirement to combine "everything as code" and manual web console changes. So the preferred way should be to treat "everything as code" or everything manually in the web console.

Would do you think of an attribute-based solution? Something like `keycloak-cli-policy: [ignore-updates, ignore-deletions]`?

**Comment by jkroepke** [comment]
I will move the topic about the flag in a issue, because this PR looks good for me.

I have to check why the graalvm will not compile. Then I will merge it.

**Pull request merged**
