### PR TITLE
Add Keycloak 24

### LINKED ISSUE #996: Keycloak 24
### Problem Statement

Keycloak 24 is not currently supported

### Proposed Solution

- Add support for Keycloak 24

### Environment

- Keycloak Version: `24.0.1`
- keycloak-config-cli Version: `5.10.0-23.0.1`

### Additional information

```
2024-03-05 12:36:03.181 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "maxTemporaryLockouts" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable (139 known properties: "userFederationMappers", "rememberMe", "duplicateEmailsAllowed", "adminEventsDetailsEnabled", "users", "clientOfflineSessionMaxLifespan", "webAuthnPolicyRequireResidentKey", "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister", "components", "otpPolicyType", "accessCodeLifespanUserAction", "id", "webAuthnPolicyAttestationConveyancePreference", "enabledEventTypes", "applications", "webAuthnPolicyPasswordlessSignatureAlgorithms", "eventsListeners", "ssoSessionMaxLifespanRememberMe", "defaultDefaultClientScopes", "webAuthnPolicyPasswordlessCreateTimeout", "clientOfflineSessionIdleTimeout", "notBefore", "publicKey", "smtpServer", "clientPolicies", "resetPasswordAllowed", "webAuthnPolicyAvoidSameAuthenticatorRegister", "accessTokenLifespanForImplicitFlow", "webAuthnPolicyPasswordlessUserVerificationRequirement", "clientScopes", "internationalizationEnabled", "defaultRole", "accessTokenLifespan", "passwordCredentialGrantAllowed", "federatedUsers", "applicationScopeMappings" [truncated]])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 1281] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["maxTemporaryLockouts"])
```

### Acceptance Criteria

_No response_

### PR DESCRIPTION
**Pull request by lme-atolcd**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

fixes #996 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [X] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by jonasvoelcker** [comment]
Hi @lme-atolcd,

as there were breaking changes in 23.0.4 we do need to add my pull request as well: https://github.com/adorsys/keycloak-config-cli/pull/977

Could you please try to merge my branch into yours and see whether everything keeps working?

I am currently stuffed with other things on the project but I will also try to add the 24 within the next week, I think ;)

Best Regards
Jonas

P.S.: @st3v0rr Could you please give a sign of life? ^^

**Comment by lme-atolcd** [comment]
Hi @jonasvoelcker 

I rebased my branch on top of yours.
Still wondering why my pull-request fails on Github CI (local tests are ok) :smile: 

```
[ERROR] de.adorsys.keycloak.config.service.GroupImportServiceTest$CreatingGroupIT.createOrUpdateGroups_shouldCreateGroup  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NoSuchMethodError: 'java.time.Instant ch.qos.logback.classic.spi.ILoggingEvent.getInstant()'
	at de.adorsys.keycloak.config.service.GroupImportServiceTest$CreatingGroupIT.createOrUpdateGroups_shouldCreateGroup(GroupImportServiceTest.java:85)
```

If you have an idea...

**Comment by jonasvoelcker** [comment]
Hi @lme-atolcd, it was exactly what @tbroyer mentioned and I downgraded it to 7.3.

Furthermore there was a change in the return values of groups so I needed to change some if-statements.

My branch seems to work now, thanks for your Feature-Flag-Analysis :)

https://github.com/adorsys/keycloak-config-cli/pull/998

**Comment by lme-atolcd** [comment]
@jonasvoelcker okay, that's good news :)
Let's continue with your pull request then.

**Pull request closed without merging**
